.PHONY=editor

editor:
	cp ../bui/target/biographer-ui.js static/biographer-editor/js/
	cp ../bui/src/main/lib/interact.js static/biographer-editor/js/
	cp ../scripts/reactome_pathways.html views/default/
	cp ../scripts/biomodels_info.html views/default/
